# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: DP_DB
    image: postgres
    ports:
      - "5432:5432"
    environment:

#      POSTGRES_USER: "${POSTGRES_USER}"
#      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
#      POSTGRES_DB: "${POSTGRES_DB}"
#      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recycling_heroes
    env_file:
      - "init.env"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
