version: '3.7'

services:
  db:
    container_name: DP_DB
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ${ENV_FILE:-./init.env}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./testData.csv:/docker-entrypoint-initdb.d/testData.csv

volumes:
  postgres-data:
